### PR TITLE
Refactor to use new lsp command and add pattern search feature

### PR DESCRIPTION
**Pull request by p4p3r**
This PR does the following:
- remove the deprecated "suggestions" feature
- use Semgrep's new `lsp` command to run the analysis and retrieve findings
- add ability to search code in the workspace using Semgrep patterns

### Security

- [ X] Change has security implications (if so, ping the security team)

### CODE REVIEW

**Comment by ajbt200128** [comment]
Closes #2

**Comment by p4p3r** [comment]
Supersedes https://github.com/returntocorp/semgrep-vscode/pull/10
(though it would be nice to port the automatic code action "Ignore line in Semgrep scans": https://github.com/returntocorp/semgrep-vscode/pull/10/files#diff-da8cc70370d67b4c482d5cf755fb7f45697844107dd73ccf7f5b54162703f63cR33

**Comment by p4p3r** [comment]
Supersedes https://github.com/returntocorp/semgrep-vscode/pull/7
(which inspired this, though we went one step further and baked LSP support into Semgrep)

**Review by ajbt200128 — APPROVED** [review]
Looks good

**Pull request merged**
