### PR TITLE
Update extension to use LSP

### PR DESCRIPTION
**Pull request by kiwiz**
Changes:
- Refactored code to use language server protocol (based on https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample/)
    - Most of the functionality now resides in `server/src`
- Remove suggestions functionality

Notes:
- Running `p/r2c-ci` takes ~8 seconds for me on average (on my netbook). Pulling down the config takes ~1.5 seconds, so a caching option for configs might be useful here.

### CODE REVIEW

**Comment by underyx** [comment]
Such an impressive PR! I'll make sure we get this in soon 😻

**Comment by chmccreery** [comment]
@cla-bot check

**Comment by chmccreery** [comment]
Hey @kiwiz I downloaded your fork here to try it out, and followed the instructions on the LSP example listed above, but I get an error (shown below) that I didn't get with the LSP example from VScode. I tried running both as "Client + Server" and as "Attach to Server". I assume you were able to run this locally as you were coding to debug- any tips on what might be different or how to run locally?

Screen Shot 2021-03-18 at 10 57 00 AM

**Comment by kiwiz** [comment]
Hi @chmccreery. For testing, I loaded up the folder in VSCode and hitting Run (F5) just worked. It should open up a new VSCode instance that the extension is running in. It doesn't show up in the Extensions sidebar, but you should see the configuration on the Settings page.

**Comment by chmccreery** [comment]
Can you verify that it still works for you? I wonder what is different about our setups

**Comment by kiwiz** [comment]
Yup, confirmed that it works on my Mac and Linux computers. Could you try building it with `vsce build` and seeing if the resulting extension installs?

**Comment by chmccreery** [comment]
I installed vsce, but get `unknown command 'build` when I run `build vsce`. I tried using `vsce package` but get the same error as above.

**Comment by kiwiz** [comment]
Hmm, it seems like your environment might not be picking up on the configs in `.vscode`?

**Comment by chmccreery** [comment]
Yeah, maybe 🙁 Let's troubleshoot together when we meet and if I still can't get it working, I will rope in another employee who has done some vscode extension work in the past. Thanks for your patience!

**Comment by chmccreery** [comment]
Hey @kiwiz, this all looks good to me so far. Can you help me by either fixing the "Server + Client" bug I was experiencing, or finding some documentation to give us confidence that this does not need to be addressed, since running "client only" worked?

**Comment by kiwiz** [comment]
I think it should be fine as long as long as `vsce package` runs successfully and the resulting package installs & runs. Here's the output I get, for ref:

```bash
$ vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> semgrep@0.3.0 vscode:prepublish
> npm run compile


> semgrep@0.3.0 compile
> tsc -b

This extension consists of 607 files, out of which 381 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /home/user/git/semgrep-vscode/semgrep-0.3.0.vsix (607 files, 901.36KB)
 INFO
The latest version of vsce is 1.87.0 and you have 1.85.0.
Update it now: npm install -g vsce
```
I don't think we made any changes there, but could you check if this works?

**Comment by chmccreery** [comment]
Great, this does seem to work! Will review the code as soon as I can and then release this into the wild 👍

**Comment by ben-elttam** [comment]
I tried to use this for as an LSP for vim with [CoC](https://github.com/neoclide/coc.nvim), but I couldn't get it to work properly.

I used this Dockerfile:

```Dockerfile
FROM node:current-alpine3.13
ADD . /app
WORKDIR /app
RUN apk add --no-cache python3 py3-pip && pip install semgrep && npm install && npm run compile
ENTRYPOINT [ "node", "server/out/server.js", "--stdio" ]
```

And this `~/.vim/coc-settings.json`:

```json
{
  "languageserver": {
    "semgrep": {
        "command": "docker",
        "args": [ "run", "-i", "berne/semgrep-lsp:latest" ],
        "filetypes": [ "py" ]
    }
  }
}
```

I'd get these logs from the docker containers:

```
Content-Length: 101

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"Semgrep version 0.47.0"}}Content-Length: 125

{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"workspace":{"workspaceFolders":{"supported":true}}}}}Content-Length: 201

{"jsonrpc":"2.0","id":0,"method":"client/registerCapability","params":{"registrations":[{"id":"f0c1be5a-0396-4a6a-aec5-d06605dd7636","method":"workspace/didChangeConfiguration","registerOptions":{}}]}}Content-Length: 204

{"jsonrpc":"2.0","id":1,"method":"client/registerCapability","params":{"registrations":[{"id":"55b25b99-bfdf-4730-ac42-53dcc166e6c7","method":"workspace/didChangeWorkspaceFolders","registerOptions":{}}]}}
```

I'd like to get a semgrep LSP working in vim/coc but I'm not sure what is needed to make it work. I don't yet properly understand LSP development.

**Comment by kiwiz** [comment]
I've been running it locally, but my config doesn't look too diferent from yours:
```json
{
    ...
    "languageserver": {
        "semgrep": {
            "module": "/home/user/git/semgrep-vscode/server/out/server.js",
            "args": ["--node-ipc"],
            "filetypes": [
                "python"
            ],
            "trace.server": "verbose"
        }
    }
}
```

**Comment by ben-elttam** [comment]
@kiwiz Thanks for posting your config, the problem was I had `filetypes: py` rather than `filetypes: python`.

**Pull request closed without merging**
